= Hi there 

Howdy! 👋 

I have over 9 years of experience working with database performance tuning & design. With my extensive exposure to AWS, SQL Server, .NET, DevOps/SRE practices, and passion for well-designed code, I bring a passion for building resilient systems.

image:https://github-readme-stats.vercel.app/api?username=sheldonhull[title="Sheldon Hull's github stats"]

== survey says 

* 🔭  I’m currently working on: AWS and minimizing the amount of chaos I generate
* 🌱  I’m currently learning: #golang and improving my serverless chops
* 👯  I’m looking to collaborate on: chatops
* 🤔  I’m looking for help with: #golang, #chatops, and #serverless
* 💬  Ask me about anything
* 📫  How to reach me: post a comment on my blog, including about page. It will automatically open a public github issue for dialogue on anything, or reach out on my blog social media links.
* 😄  Pronouns: he/him


== Fellow Dev FAQ:

* _Preferred Editor:_ Visual Studio Code
* _Light or Dark Theme:_ Dark, of course. Currently using City Lights Dark Theme.
* _Spaces or Tabs:_ Spaces, simply because most of the tooling in the DevOps arena expects it. Font: Jet Brains Mono & FuraCode Nerd Font Mono (ligature based font)
* _Source Control:_ Git
* _Automation:_ Azure DevOps, GitHub Actions (GitLab also seems promising)
* _Preferred Computer Setup:_ Ultrawide, mechanical keyboard, and latte...
* _Blog:_ As time permits, sheldonhull.com, though most projects I've done are not public 
* _Terminal:_ macOS Iterm2, Windows 10 - The newer Windows Terminal. Starship for prompt.
* _If I was an emoji I'd be:_ 🌮🌮🌮


credit:
* link:https://github.com/anuraghazra/github-readme-stats[github-readme-stats]
